### ISSUE TITLE
Typescript files support (.ts, .tsx files)

### ISSUE THREAD

**Issue by saudraisn** [ferdelamad/styled-snippets#13]
Hi! Would it be possible to enable this extension (very nice one btw) in typescript files (.ts, .tsx)?

Thanks in advance!

**Comment by ferdelamad** [comment]
Hi @saudraisn sorry for the late response! I'm currently working on the next version of it and I will try to include typescript support. Thanks for the feedback :D!

**Comment by ferdelamad** [comment]
@saudraisn probably v2 will be ready at the end of the week and this issue seemed like an easy fix so I updated to v1.0.3 supporting both `.ts` and `.tsx`.
Let me know if you have any issues, thanks for the support :).

**Comment by saudraisn** [comment]
Amazing, thanks! :rocket:
